// <auto-generated />
namespace WindowsEFDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class avanzando : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(avanzando));
        
        string IMigrationMetadata.Id
        {
            get { return "202301181938209_avanzando"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
